# First stage: build war file
#==================================================================================================
FROM maven:3.8.6-openjdk-8-slim as builder

# Copy all files into root's home, including the source, pom file, ./m2 directory and credentials
RUN mkdir ckg_agents


# Populate settings templates with credentials, repo name
ADD ../.m2 /ckg_agents/.m2
ADD . /ckg_agents/agents
ADD ../access_agent_setup /ckg_agents/access_agent_setup
ADD ../impexp-client /ckg_agents/impexp-client
ADD ../impexp-client-common /ckg_agents/impexp-client-common
ADD ../impexp-config /ckg_agents/impexp-config
ADD ../impexp-core /ckg_agents/impexp-core
ADD ../impexp-kml-collada-plugin /ckg_agents/impexp-kml-collada-plugin
ADD ../impexp-plugin-api /ckg_agents/impexp-plugin-api
ADD ../utils /ckg_agents/utils
ADD ../pom.xml /ckg_agents_code


WORKDIR /ckg_agents_code
# build
#RUN --mount=type=cache mvn initialize
RUN --mount=type=cache,target=/webapps mvn clean install -DskipTests

LABEL maintainer="shiying.li@sec.ethz.ch"
#==================================================================================================

# Second stage: copy the downloaded dependency into a new image and build into an app
#==================================================================================================
FROM tomcat:9.0 as agent

COPY --from=builder /webapps/agents##0.3.1.war $CATALINA_HOME/webapps/
#COPY --from=builder /access_agent_setup /ckg_agents_code/access_agent_setup
COPY --from=builder /ckg_agents_code /ckg_agents_code

EXPOSE 8080

WORKDIR /bin
# Start the Tomcat server
ENTRYPOINT ["catalina.sh", "run"]
#==================================================================================================