version: "1.0.0"

services:
  backend:
    image: ckg-agent:1.0.0
    container_name: ckg-agent
    pull_policy: if_not_present
    build:
      context: "./ckg_agents_code"
    # expose
    ports:
      - "5000:8080"
    environment:
      LOG4J_FORMAT_MSG_NO_LOOKUPS: "true"


