version: "1.0.0"

services:
  backend:
    image: ckg-agent:1.0.0
    container_name: ckg-agent
    pull_policy: if_not_present
    build:
      context: "./ckg_agents_code"
    # expose
    ports:
      - "8080:8080"
    environment:
      LOG4J_FORMAT_MSG_NO_LOOKUPS: "true"


  frontend:
    image: nodejs:1.0.0
    container_name: nodejs
    pull_policy: if_not_present
    build:
      context: "./3dcitydb-web-map-1.9.0"
    # expose
    ports:
      - "8000:8000"
    environment:
      LOG4J_FORMAT_MSG_NO_LOOKUPS: "true"