POST http://localhost:8080/agents/distance
Content-Type: application/json

{"iris":["http://www.theworldavatar.com:83/citieskg/namespace/berlin/sparql/cityobject/BLDG_000300000007fadb/", "http://www.theworldavatar.com:83/citieskg/namespace/berlin/sparql/cityobject/BLDG_00030000000779b5/"]}