POST http://localhost:8080/agents/import/source
Content-Type: application/json

{"directory":"/Library/tomcat/import",
  "targetURL": "http://192.168.0.101:9999/blazegraph/namespace/onemapsgEPSG24500/sparql",
  "srid": "24500",
  "srsName": "EPSG:24500"}