POST http://localhost:8080/agents/import/source
Content-Type: application/json

{"directory":"C:\\tmp\\import",
  "targetURL": "http://127.0.0.1:9999/blazegraph/namespace/testdata/sparql",
  "srid": "25833",
  "srsName": "EPSG:25833"}