- script: create-new-scenario
  parameters:
    project: testProject
    scenario: testScenario
    output-path: directory_path
    zone: filepath_zone
    terrain:
    streets:
- script: weather-helper
  parameters:
    scenario: scenario_path
    weather: Singapore-Changi_1990_2010_TMY
- script: surroundings-helper
  parameters:
    scenario: scenario_path
    buffer: 50.
- script: terrain-helper
  parameters:
    scenario: scenario_path
- script: data-initializer
  parameters:
    scenario: scenario_path
    databases-path: SG
- script: archetypes-mapper
  parameters:
    scenario: scenario_path
    buildings: ['B001']
- script: radiation
  parameters:
    scenario: scenario_path
    buildings: ['B001']
- script: schedule-maker
  parameters:
    scenario: scenario_path
    buildings: ['B001']
- script: demand
  parameters:
    scenario: scenario_path
    buildings: ['B001']
    loads-output: ['GRID', 'QH_sys', 'QC_sys', 'E_sys']
    massflows-output: []
    temperatures-output: []
- script: photovoltaic
  parameters:
    scenario: scenario_path
    buildings: ['B001']