# First stage: build war file
#==================================================================================================
FROM maven:3.8.6-openjdk-8-slim as builder

# Copy all files into root's home, including the source, pom file, ./m2 directory and credentials
ADD . /root

# Skip the build process for testing purpose

LABEL maintainer="shiying.li@sec.ethz.ch"
#==================================================================================================

# Second stage: copy the downloaded dependency into a new image and build into an app
#==================================================================================================
FROM tomcat:9.0 as agent

WORKDIR /bin

COPY --from=builder /root/webapps/agents##0.3.1.war $CATALINA_HOME/webapps/

EXPOSE 8080

# Start the Tomcat server
CMD ["catalina.sh", "run"]
#==================================================================================================