# This dockerfile requires pre-built war file located in webapps/ directory, which will be copied into docker.


# First stage: Add the source directory including war file into docker
#==================================================================================================
FROM maven:3.8.6-openjdk-8-slim as builder

# Copy all files into root's home, including the source, pom file, ./m2 directory and credentials
ADD . /root

LABEL maintainer="shiying.li@sec.ethz.ch"
#==================================================================================================

# Second stage: copy the pre-built war file into a new image and build into an app
#==================================================================================================
FROM tomcat:9.0 as agent

COPY --from=builder /root/webapps/agents##0.3.1.war $CATALINA_HOME/webapps/

EXPOSE 8080

WORKDIR /bin

# Start the Tomcat server
ENTRYPOINT ["catalina.sh", "run"]
#==================================================================================================