# First stage: build war file
#==================================================================================================
FROM maven:3.8.6-openjdk-8-slim as builder

# Copy all files into root's home, including the source, pom file, ./m2 directory and credentials
ADD ./ /root/agents

# Populate settings templates with credentials, repo name
#ADD ../.m2 /root/.m2
#COPY ../impexp-client /root/impexp-client
#ADD ../impexp-client-common /root/impexp-client-common
#ADD ../impexp-config /root/impexp-config
#ADD ../impexp-core /root/impexp-core
#ADD ../impexp-kml-collada-plugin /root/impexp-kml-collada-plugin
#ADD ../impexp-plugin-api /root/impexp-plugin-api
#ADD ../utils /root/utils
ADD ../pom.xml /root/pom.xml

# build
WORKDIR /root
#RUN --mount=type=cache,target=/root/webapps mvn clean install -DskipTests

LABEL maintainer="shiying.li@sec.ethz.ch"
#==================================================================================================

# Second stage: copy the downloaded dependency into a new image and build into an app
#==================================================================================================
FROM tomcat:9.0 as agent

WORKDIR /bin

COPY --from=builder /root/agents/webapps/agents##0.3.1.war $CATALINA_HOME/webapps/

EXPOSE 8080

# Start the Tomcat server
ENTRYPOINT ["catalina.sh", "run"]
#==================================================================================================