version: "1.0.0"

services:
  cityinformation-agent:
    image: cia-agent:1.0.0
    container_name: cia-agent
    pull_policy: if_not_present
    build:
      context: "agents"
      dockerfile: "./Dockerfile"
    # expose
    ports:
      - "5000:8080"
    environment:
      LOG4J_FORMAT_MSG_NO_LOOKUPS: "true"
    volumes:
      - ./src/main/resources/config.properties:/src/main/resources/config.properties
